/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as FounderIdRouteImport } from './routes/founder.$id'
import { Route as EventsSlugRouteImport } from './routes/events/$slug'
import { Route as AuthenticatedWorkRouteImport } from './routes/_authenticated/work'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedVenturesRouteImport } from './routes/_authenticated/ventures'
import { Route as AuthenticatedVantageRouteImport } from './routes/_authenticated/vantage'
import { Route as AuthenticatedStakesRouteImport } from './routes/_authenticated/stakes'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedPitchathonsRouteImport } from './routes/_authenticated/pitchathons'
import { Route as AuthenticatedPitchDeckRouteImport } from './routes/_authenticated/pitch-deck'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedLoansRouteImport } from './routes/_authenticated/loans'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedKycRouteImport } from './routes/_authenticated/kyc'
import { Route as AuthenticatedJudgeRouteImport } from './routes/_authenticated/judge'
import { Route as AuthenticatedInvestorRouteImport } from './routes/_authenticated/investor'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedDemoRouteImport } from './routes/_authenticated/demo'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedBuilderRouteImport } from './routes/_authenticated/builder'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAcademyRouteImport } from './routes/_authenticated/academy'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages/index'
import { Route as AuthenticatedCapitalIndexRouteImport } from './routes/_authenticated/capital/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedOnboardingBuilderRouteImport } from './routes/_authenticated/onboarding/builder'
import { Route as AuthenticatedMessagesIdRouteImport } from './routes/_authenticated/messages/$id'
import { Route as AuthenticatedJoinCodeRouteImport } from './routes/_authenticated/join.$code'
import { Route as AuthenticatedDiscoverCommunitiesRouteImport } from './routes/_authenticated/discover/communities'
import { Route as AuthenticatedDemoIdRouteImport } from './routes/_authenticated/demo.$id'
import { Route as AuthenticatedDealsIdRouteImport } from './routes/_authenticated/deals.$id'
import { Route as AuthenticatedCommunityChannelsRouteImport } from './routes/_authenticated/community/channels'
import { Route as AuthenticatedCommunityChallengesRouteImport } from './routes/_authenticated/community/challenges'
import { Route as AuthenticatedCapitalPortfolioRouteImport } from './routes/_authenticated/capital/portfolio'
import { Route as AuthenticatedCIdRouteImport } from './routes/_authenticated/c.$id'
import { Route as AuthenticatedBuilderIdRouteImport } from './routes/_authenticated/builder/$id'
import { Route as AuthenticatedAdminWalletsRouteImport } from './routes/_authenticated/admin/wallets'
import { Route as AuthenticatedAdminTokensRouteImport } from './routes/_authenticated/admin/tokens'
import { Route as AuthenticatedAdminTestWebhookRouteImport } from './routes/_authenticated/admin/test-webhook'
import { Route as AuthenticatedAdminSessionsRouteImport } from './routes/_authenticated/admin/sessions'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin/roles'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin/permissions'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin/members'
import { Route as AuthenticatedAdminIntegrationsRouteImport } from './routes/_authenticated/admin/integrations'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin/courses'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderIdRoute = FounderIdRouteImport.update({
  id: '/founder/$id',
  path: '/founder/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkRoute = AuthenticatedWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVenturesRoute = AuthenticatedVenturesRouteImport.update({
  id: '/ventures',
  path: '/ventures',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVantageRoute = AuthenticatedVantageRouteImport.update({
  id: '/vantage',
  path: '/vantage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStakesRoute = AuthenticatedStakesRouteImport.update({
  id: '/stakes',
  path: '/stakes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPitchathonsRoute =
  AuthenticatedPitchathonsRouteImport.update({
    id: '/pitchathons',
    path: '/pitchathons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPitchDeckRoute = AuthenticatedPitchDeckRouteImport.update({
  id: '/pitch-deck',
  path: '/pitch-deck',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoansRoute = AuthenticatedLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKycRoute = AuthenticatedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJudgeRoute = AuthenticatedJudgeRouteImport.update({
  id: '/judge',
  path: '/judge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestorRoute = AuthenticatedInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemoRoute = AuthenticatedDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuilderRoute = AuthenticatedBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcademyRoute = AuthenticatedAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCapitalIndexRoute =
  AuthenticatedCapitalIndexRouteImport.update({
    id: '/capital/',
    path: '/capital/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedOnboardingBuilderRoute =
  AuthenticatedOnboardingBuilderRouteImport.update({
    id: '/builder',
    path: '/builder',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedMessagesIdRoute = AuthenticatedMessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJoinCodeRoute = AuthenticatedJoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverCommunitiesRoute =
  AuthenticatedDiscoverCommunitiesRouteImport.update({
    id: '/communities',
    path: '/communities',
    getParentRoute: () => AuthenticatedDiscoverRoute,
  } as any)
const AuthenticatedDemoIdRoute = AuthenticatedDemoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDemoRoute,
} as any)
const AuthenticatedDealsIdRoute = AuthenticatedDealsIdRouteImport.update({
  id: '/deals/$id',
  path: '/deals/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityChannelsRoute =
  AuthenticatedCommunityChannelsRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedCommunityChallengesRoute =
  AuthenticatedCommunityChallengesRouteImport.update({
    id: '/challenges',
    path: '/challenges',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedCapitalPortfolioRoute =
  AuthenticatedCapitalPortfolioRouteImport.update({
    id: '/capital/portfolio',
    path: '/capital/portfolio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCIdRoute = AuthenticatedCIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuilderIdRoute = AuthenticatedBuilderIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBuilderRoute,
} as any)
const AuthenticatedAdminWalletsRoute =
  AuthenticatedAdminWalletsRouteImport.update({
    id: '/wallets',
    path: '/wallets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTokensRoute =
  AuthenticatedAdminTokensRouteImport.update({
    id: '/tokens',
    path: '/tokens',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTestWebhookRoute =
  AuthenticatedAdminTestWebhookRouteImport.update({
    id: '/test-webhook',
    path: '/test-webhook',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSessionsRoute =
  AuthenticatedAdminSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIntegrationsRoute =
  AuthenticatedAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/communities': typeof CommunitiesRoute
  '/investors': typeof InvestorsRoute
  '/journey': typeof JourneyRoute
  '/operator': typeof OperatorRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/academy': typeof AuthenticatedAcademyRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/builder': typeof AuthenticatedBuilderRouteWithChildren
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/community': typeof AuthenticatedCommunityRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demo': typeof AuthenticatedDemoRouteWithChildren
  '/discover': typeof AuthenticatedDiscoverRouteWithChildren
  '/help': typeof AuthenticatedHelpRoute
  '/investor': typeof AuthenticatedInvestorRoute
  '/judge': typeof AuthenticatedJudgeRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/pitch-deck': typeof AuthenticatedPitchDeckRoute
  '/pitchathons': typeof AuthenticatedPitchathonsRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stakes': typeof AuthenticatedStakesRoute
  '/vantage': typeof AuthenticatedVantageRoute
  '/ventures': typeof AuthenticatedVenturesRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/work': typeof AuthenticatedWorkRoute
  '/events/$slug': typeof EventsSlugRoute
  '/founder/$id': typeof FounderIdRoute
  '/events/': typeof EventsIndexRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/admin/test-webhook': typeof AuthenticatedAdminTestWebhookRoute
  '/admin/tokens': typeof AuthenticatedAdminTokensRoute
  '/admin/wallets': typeof AuthenticatedAdminWalletsRoute
  '/builder/$id': typeof AuthenticatedBuilderIdRoute
  '/c/$id': typeof AuthenticatedCIdRoute
  '/capital/portfolio': typeof AuthenticatedCapitalPortfolioRoute
  '/community/challenges': typeof AuthenticatedCommunityChallengesRoute
  '/community/channels': typeof AuthenticatedCommunityChannelsRoute
  '/deals/$id': typeof AuthenticatedDealsIdRoute
  '/demo/$id': typeof AuthenticatedDemoIdRoute
  '/discover/communities': typeof AuthenticatedDiscoverCommunitiesRoute
  '/join/$code': typeof AuthenticatedJoinCodeRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/onboarding/builder': typeof AuthenticatedOnboardingBuilderRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/capital/': typeof AuthenticatedCapitalIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/communities': typeof CommunitiesRoute
  '/investors': typeof InvestorsRoute
  '/journey': typeof JourneyRoute
  '/operator': typeof OperatorRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/academy': typeof AuthenticatedAcademyRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/builder': typeof AuthenticatedBuilderRouteWithChildren
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/community': typeof AuthenticatedCommunityRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demo': typeof AuthenticatedDemoRouteWithChildren
  '/discover': typeof AuthenticatedDiscoverRouteWithChildren
  '/help': typeof AuthenticatedHelpRoute
  '/investor': typeof AuthenticatedInvestorRoute
  '/judge': typeof AuthenticatedJudgeRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/pitch-deck': typeof AuthenticatedPitchDeckRoute
  '/pitchathons': typeof AuthenticatedPitchathonsRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stakes': typeof AuthenticatedStakesRoute
  '/vantage': typeof AuthenticatedVantageRoute
  '/ventures': typeof AuthenticatedVenturesRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/work': typeof AuthenticatedWorkRoute
  '/events/$slug': typeof EventsSlugRoute
  '/founder/$id': typeof FounderIdRoute
  '/events': typeof EventsIndexRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/admin/test-webhook': typeof AuthenticatedAdminTestWebhookRoute
  '/admin/tokens': typeof AuthenticatedAdminTokensRoute
  '/admin/wallets': typeof AuthenticatedAdminWalletsRoute
  '/builder/$id': typeof AuthenticatedBuilderIdRoute
  '/c/$id': typeof AuthenticatedCIdRoute
  '/capital/portfolio': typeof AuthenticatedCapitalPortfolioRoute
  '/community/challenges': typeof AuthenticatedCommunityChallengesRoute
  '/community/channels': typeof AuthenticatedCommunityChannelsRoute
  '/deals/$id': typeof AuthenticatedDealsIdRoute
  '/demo/$id': typeof AuthenticatedDemoIdRoute
  '/discover/communities': typeof AuthenticatedDiscoverCommunitiesRoute
  '/join/$code': typeof AuthenticatedJoinCodeRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/onboarding/builder': typeof AuthenticatedOnboardingBuilderRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/capital': typeof AuthenticatedCapitalIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/communities': typeof CommunitiesRoute
  '/investors': typeof InvestorsRoute
  '/journey': typeof JourneyRoute
  '/operator': typeof OperatorRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/academy': typeof AuthenticatedAcademyRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/builder': typeof AuthenticatedBuilderRouteWithChildren
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/demo': typeof AuthenticatedDemoRouteWithChildren
  '/_authenticated/discover': typeof AuthenticatedDiscoverRouteWithChildren
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/investor': typeof AuthenticatedInvestorRoute
  '/_authenticated/judge': typeof AuthenticatedJudgeRoute
  '/_authenticated/kyc': typeof AuthenticatedKycRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/loans': typeof AuthenticatedLoansRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/_authenticated/pitch-deck': typeof AuthenticatedPitchDeckRoute
  '/_authenticated/pitchathons': typeof AuthenticatedPitchathonsRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stakes': typeof AuthenticatedStakesRoute
  '/_authenticated/vantage': typeof AuthenticatedVantageRoute
  '/_authenticated/ventures': typeof AuthenticatedVenturesRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/work': typeof AuthenticatedWorkRoute
  '/events/$slug': typeof EventsSlugRoute
  '/founder/$id': typeof FounderIdRoute
  '/events/': typeof EventsIndexRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/_authenticated/admin/test-webhook': typeof AuthenticatedAdminTestWebhookRoute
  '/_authenticated/admin/tokens': typeof AuthenticatedAdminTokensRoute
  '/_authenticated/admin/wallets': typeof AuthenticatedAdminWalletsRoute
  '/_authenticated/builder/$id': typeof AuthenticatedBuilderIdRoute
  '/_authenticated/c/$id': typeof AuthenticatedCIdRoute
  '/_authenticated/capital/portfolio': typeof AuthenticatedCapitalPortfolioRoute
  '/_authenticated/community/challenges': typeof AuthenticatedCommunityChallengesRoute
  '/_authenticated/community/channels': typeof AuthenticatedCommunityChannelsRoute
  '/_authenticated/deals/$id': typeof AuthenticatedDealsIdRoute
  '/_authenticated/demo/$id': typeof AuthenticatedDemoIdRoute
  '/_authenticated/discover/communities': typeof AuthenticatedDiscoverCommunitiesRoute
  '/_authenticated/join/$code': typeof AuthenticatedJoinCodeRoute
  '/_authenticated/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/_authenticated/onboarding/builder': typeof AuthenticatedOnboardingBuilderRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/capital/': typeof AuthenticatedCapitalIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/auth'
    | '/auth-callback'
    | '/communities'
    | '/investors'
    | '/journey'
    | '/operator'
    | '/platform'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/academy'
    | '/analytics'
    | '/builder'
    | '/certificates'
    | '/community'
    | '/dashboard'
    | '/demo'
    | '/discover'
    | '/help'
    | '/investor'
    | '/judge'
    | '/kyc'
    | '/leaderboard'
    | '/loans'
    | '/marketplace'
    | '/meetings'
    | '/notifications'
    | '/onboarding'
    | '/pitch-deck'
    | '/pitchathons'
    | '/portfolio'
    | '/profile'
    | '/referrals'
    | '/search'
    | '/sessions'
    | '/settings'
    | '/stakes'
    | '/vantage'
    | '/ventures'
    | '/wallet'
    | '/work'
    | '/events/$slug'
    | '/founder/$id'
    | '/events/'
    | '/admin/courses'
    | '/admin/integrations'
    | '/admin/members'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/sessions'
    | '/admin/test-webhook'
    | '/admin/tokens'
    | '/admin/wallets'
    | '/builder/$id'
    | '/c/$id'
    | '/capital/portfolio'
    | '/community/challenges'
    | '/community/channels'
    | '/deals/$id'
    | '/demo/$id'
    | '/discover/communities'
    | '/join/$code'
    | '/messages/$id'
    | '/onboarding/builder'
    | '/admin/'
    | '/capital/'
    | '/messages/'
    | '/api/public/webhooks/paystack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/auth'
    | '/auth-callback'
    | '/communities'
    | '/investors'
    | '/journey'
    | '/operator'
    | '/platform'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/academy'
    | '/analytics'
    | '/builder'
    | '/certificates'
    | '/community'
    | '/dashboard'
    | '/demo'
    | '/discover'
    | '/help'
    | '/investor'
    | '/judge'
    | '/kyc'
    | '/leaderboard'
    | '/loans'
    | '/marketplace'
    | '/meetings'
    | '/notifications'
    | '/onboarding'
    | '/pitch-deck'
    | '/pitchathons'
    | '/portfolio'
    | '/profile'
    | '/referrals'
    | '/search'
    | '/sessions'
    | '/settings'
    | '/stakes'
    | '/vantage'
    | '/ventures'
    | '/wallet'
    | '/work'
    | '/events/$slug'
    | '/founder/$id'
    | '/events'
    | '/admin/courses'
    | '/admin/integrations'
    | '/admin/members'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/sessions'
    | '/admin/test-webhook'
    | '/admin/tokens'
    | '/admin/wallets'
    | '/builder/$id'
    | '/c/$id'
    | '/capital/portfolio'
    | '/community/challenges'
    | '/community/channels'
    | '/deals/$id'
    | '/demo/$id'
    | '/discover/communities'
    | '/join/$code'
    | '/messages/$id'
    | '/onboarding/builder'
    | '/admin'
    | '/capital'
    | '/messages'
    | '/api/public/webhooks/paystack'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/about'
    | '/auth'
    | '/auth-callback'
    | '/communities'
    | '/investors'
    | '/journey'
    | '/operator'
    | '/platform'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/academy'
    | '/_authenticated/analytics'
    | '/_authenticated/builder'
    | '/_authenticated/certificates'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/demo'
    | '/_authenticated/discover'
    | '/_authenticated/help'
    | '/_authenticated/investor'
    | '/_authenticated/judge'
    | '/_authenticated/kyc'
    | '/_authenticated/leaderboard'
    | '/_authenticated/loans'
    | '/_authenticated/marketplace'
    | '/_authenticated/meetings'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/pitch-deck'
    | '/_authenticated/pitchathons'
    | '/_authenticated/portfolio'
    | '/_authenticated/profile'
    | '/_authenticated/referrals'
    | '/_authenticated/search'
    | '/_authenticated/sessions'
    | '/_authenticated/settings'
    | '/_authenticated/stakes'
    | '/_authenticated/vantage'
    | '/_authenticated/ventures'
    | '/_authenticated/wallet'
    | '/_authenticated/work'
    | '/events/$slug'
    | '/founder/$id'
    | '/events/'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/integrations'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/sessions'
    | '/_authenticated/admin/test-webhook'
    | '/_authenticated/admin/tokens'
    | '/_authenticated/admin/wallets'
    | '/_authenticated/builder/$id'
    | '/_authenticated/c/$id'
    | '/_authenticated/capital/portfolio'
    | '/_authenticated/community/challenges'
    | '/_authenticated/community/channels'
    | '/_authenticated/deals/$id'
    | '/_authenticated/demo/$id'
    | '/_authenticated/discover/communities'
    | '/_authenticated/join/$code'
    | '/_authenticated/messages/$id'
    | '/_authenticated/onboarding/builder'
    | '/_authenticated/admin/'
    | '/_authenticated/capital/'
    | '/_authenticated/messages/'
    | '/api/public/webhooks/paystack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CommunitiesRoute: typeof CommunitiesRoute
  InvestorsRoute: typeof InvestorsRoute
  JourneyRoute: typeof JourneyRoute
  OperatorRoute: typeof OperatorRoute
  PlatformRoute: typeof PlatformRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  EventsSlugRoute: typeof EventsSlugRoute
  FounderIdRoute: typeof FounderIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/$id': {
      id: '/founder/$id'
      path: '/founder/$id'
      fullPath: '/founder/$id'
      preLoaderRoute: typeof FounderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/work': {
      id: '/_authenticated/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof AuthenticatedWorkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventures': {
      id: '/_authenticated/ventures'
      path: '/ventures'
      fullPath: '/ventures'
      preLoaderRoute: typeof AuthenticatedVenturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vantage': {
      id: '/_authenticated/vantage'
      path: '/vantage'
      fullPath: '/vantage'
      preLoaderRoute: typeof AuthenticatedVantageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stakes': {
      id: '/_authenticated/stakes'
      path: '/stakes'
      fullPath: '/stakes'
      preLoaderRoute: typeof AuthenticatedStakesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pitchathons': {
      id: '/_authenticated/pitchathons'
      path: '/pitchathons'
      fullPath: '/pitchathons'
      preLoaderRoute: typeof AuthenticatedPitchathonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pitch-deck': {
      id: '/_authenticated/pitch-deck'
      path: '/pitch-deck'
      fullPath: '/pitch-deck'
      preLoaderRoute: typeof AuthenticatedPitchDeckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loans': {
      id: '/_authenticated/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthenticatedLoansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kyc': {
      id: '/_authenticated/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthenticatedKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/judge': {
      id: '/_authenticated/judge'
      path: '/judge'
      fullPath: '/judge'
      preLoaderRoute: typeof AuthenticatedJudgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investor': {
      id: '/_authenticated/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof AuthenticatedInvestorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo': {
      id: '/_authenticated/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof AuthenticatedDemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/builder': {
      id: '/_authenticated/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AuthenticatedBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academy': {
      id: '/_authenticated/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AuthenticatedAcademyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capital/': {
      id: '/_authenticated/capital/'
      path: '/capital'
      fullPath: '/capital/'
      preLoaderRoute: typeof AuthenticatedCapitalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/onboarding/builder': {
      id: '/_authenticated/onboarding/builder'
      path: '/builder'
      fullPath: '/onboarding/builder'
      preLoaderRoute: typeof AuthenticatedOnboardingBuilderRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/messages/$id': {
      id: '/_authenticated/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthenticatedMessagesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/join/$code': {
      id: '/_authenticated/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof AuthenticatedJoinCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover/communities': {
      id: '/_authenticated/discover/communities'
      path: '/communities'
      fullPath: '/discover/communities'
      preLoaderRoute: typeof AuthenticatedDiscoverCommunitiesRouteImport
      parentRoute: typeof AuthenticatedDiscoverRoute
    }
    '/_authenticated/demo/$id': {
      id: '/_authenticated/demo/$id'
      path: '/$id'
      fullPath: '/demo/$id'
      preLoaderRoute: typeof AuthenticatedDemoIdRouteImport
      parentRoute: typeof AuthenticatedDemoRoute
    }
    '/_authenticated/deals/$id': {
      id: '/_authenticated/deals/$id'
      path: '/deals/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof AuthenticatedDealsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community/channels': {
      id: '/_authenticated/community/channels'
      path: '/channels'
      fullPath: '/community/channels'
      preLoaderRoute: typeof AuthenticatedCommunityChannelsRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/community/challenges': {
      id: '/_authenticated/community/challenges'
      path: '/challenges'
      fullPath: '/community/challenges'
      preLoaderRoute: typeof AuthenticatedCommunityChallengesRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/capital/portfolio': {
      id: '/_authenticated/capital/portfolio'
      path: '/capital/portfolio'
      fullPath: '/capital/portfolio'
      preLoaderRoute: typeof AuthenticatedCapitalPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/c/$id': {
      id: '/_authenticated/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof AuthenticatedCIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/builder/$id': {
      id: '/_authenticated/builder/$id'
      path: '/$id'
      fullPath: '/builder/$id'
      preLoaderRoute: typeof AuthenticatedBuilderIdRouteImport
      parentRoute: typeof AuthenticatedBuilderRoute
    }
    '/_authenticated/admin/wallets': {
      id: '/_authenticated/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AuthenticatedAdminWalletsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tokens': {
      id: '/_authenticated/admin/tokens'
      path: '/tokens'
      fullPath: '/admin/tokens'
      preLoaderRoute: typeof AuthenticatedAdminTokensRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/test-webhook': {
      id: '/_authenticated/admin/test-webhook'
      path: '/test-webhook'
      fullPath: '/admin/test-webhook'
      preLoaderRoute: typeof AuthenticatedAdminTestWebhookRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sessions': {
      id: '/_authenticated/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AuthenticatedAdminSessionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/integrations': {
      id: '/_authenticated/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminIntegrationsRoute: typeof AuthenticatedAdminIntegrationsRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSessionsRoute: typeof AuthenticatedAdminSessionsRoute
  AuthenticatedAdminTestWebhookRoute: typeof AuthenticatedAdminTestWebhookRoute
  AuthenticatedAdminTokensRoute: typeof AuthenticatedAdminTokensRoute
  AuthenticatedAdminWalletsRoute: typeof AuthenticatedAdminWalletsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
    AuthenticatedAdminIntegrationsRoute: AuthenticatedAdminIntegrationsRoute,
    AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
    AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
    AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
    AuthenticatedAdminSessionsRoute: AuthenticatedAdminSessionsRoute,
    AuthenticatedAdminTestWebhookRoute: AuthenticatedAdminTestWebhookRoute,
    AuthenticatedAdminTokensRoute: AuthenticatedAdminTokensRoute,
    AuthenticatedAdminWalletsRoute: AuthenticatedAdminWalletsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedBuilderRouteChildren {
  AuthenticatedBuilderIdRoute: typeof AuthenticatedBuilderIdRoute
}

const AuthenticatedBuilderRouteChildren: AuthenticatedBuilderRouteChildren = {
  AuthenticatedBuilderIdRoute: AuthenticatedBuilderIdRoute,
}

const AuthenticatedBuilderRouteWithChildren =
  AuthenticatedBuilderRoute._addFileChildren(AuthenticatedBuilderRouteChildren)

interface AuthenticatedCommunityRouteChildren {
  AuthenticatedCommunityChallengesRoute: typeof AuthenticatedCommunityChallengesRoute
  AuthenticatedCommunityChannelsRoute: typeof AuthenticatedCommunityChannelsRoute
}

const AuthenticatedCommunityRouteChildren: AuthenticatedCommunityRouteChildren =
  {
    AuthenticatedCommunityChallengesRoute:
      AuthenticatedCommunityChallengesRoute,
    AuthenticatedCommunityChannelsRoute: AuthenticatedCommunityChannelsRoute,
  }

const AuthenticatedCommunityRouteWithChildren =
  AuthenticatedCommunityRoute._addFileChildren(
    AuthenticatedCommunityRouteChildren,
  )

interface AuthenticatedDemoRouteChildren {
  AuthenticatedDemoIdRoute: typeof AuthenticatedDemoIdRoute
}

const AuthenticatedDemoRouteChildren: AuthenticatedDemoRouteChildren = {
  AuthenticatedDemoIdRoute: AuthenticatedDemoIdRoute,
}

const AuthenticatedDemoRouteWithChildren =
  AuthenticatedDemoRoute._addFileChildren(AuthenticatedDemoRouteChildren)

interface AuthenticatedDiscoverRouteChildren {
  AuthenticatedDiscoverCommunitiesRoute: typeof AuthenticatedDiscoverCommunitiesRoute
}

const AuthenticatedDiscoverRouteChildren: AuthenticatedDiscoverRouteChildren = {
  AuthenticatedDiscoverCommunitiesRoute: AuthenticatedDiscoverCommunitiesRoute,
}

const AuthenticatedDiscoverRouteWithChildren =
  AuthenticatedDiscoverRoute._addFileChildren(
    AuthenticatedDiscoverRouteChildren,
  )

interface AuthenticatedOnboardingRouteChildren {
  AuthenticatedOnboardingBuilderRoute: typeof AuthenticatedOnboardingBuilderRoute
}

const AuthenticatedOnboardingRouteChildren: AuthenticatedOnboardingRouteChildren =
  {
    AuthenticatedOnboardingBuilderRoute: AuthenticatedOnboardingBuilderRoute,
  }

const AuthenticatedOnboardingRouteWithChildren =
  AuthenticatedOnboardingRoute._addFileChildren(
    AuthenticatedOnboardingRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAcademyRoute: typeof AuthenticatedAcademyRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBuilderRoute: typeof AuthenticatedBuilderRouteWithChildren
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDemoRoute: typeof AuthenticatedDemoRouteWithChildren
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRouteWithChildren
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedInvestorRoute: typeof AuthenticatedInvestorRoute
  AuthenticatedJudgeRoute: typeof AuthenticatedJudgeRoute
  AuthenticatedKycRoute: typeof AuthenticatedKycRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedLoansRoute: typeof AuthenticatedLoansRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRouteWithChildren
  AuthenticatedPitchDeckRoute: typeof AuthenticatedPitchDeckRoute
  AuthenticatedPitchathonsRoute: typeof AuthenticatedPitchathonsRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStakesRoute: typeof AuthenticatedStakesRoute
  AuthenticatedVantageRoute: typeof AuthenticatedVantageRoute
  AuthenticatedVenturesRoute: typeof AuthenticatedVenturesRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWorkRoute: typeof AuthenticatedWorkRoute
  AuthenticatedCIdRoute: typeof AuthenticatedCIdRoute
  AuthenticatedCapitalPortfolioRoute: typeof AuthenticatedCapitalPortfolioRoute
  AuthenticatedDealsIdRoute: typeof AuthenticatedDealsIdRoute
  AuthenticatedJoinCodeRoute: typeof AuthenticatedJoinCodeRoute
  AuthenticatedMessagesIdRoute: typeof AuthenticatedMessagesIdRoute
  AuthenticatedCapitalIndexRoute: typeof AuthenticatedCapitalIndexRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAcademyRoute: AuthenticatedAcademyRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBuilderRoute: AuthenticatedBuilderRouteWithChildren,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDemoRoute: AuthenticatedDemoRouteWithChildren,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRouteWithChildren,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedInvestorRoute: AuthenticatedInvestorRoute,
  AuthenticatedJudgeRoute: AuthenticatedJudgeRoute,
  AuthenticatedKycRoute: AuthenticatedKycRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedLoansRoute: AuthenticatedLoansRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRouteWithChildren,
  AuthenticatedPitchDeckRoute: AuthenticatedPitchDeckRoute,
  AuthenticatedPitchathonsRoute: AuthenticatedPitchathonsRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStakesRoute: AuthenticatedStakesRoute,
  AuthenticatedVantageRoute: AuthenticatedVantageRoute,
  AuthenticatedVenturesRoute: AuthenticatedVenturesRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWorkRoute: AuthenticatedWorkRoute,
  AuthenticatedCIdRoute: AuthenticatedCIdRoute,
  AuthenticatedCapitalPortfolioRoute: AuthenticatedCapitalPortfolioRoute,
  AuthenticatedDealsIdRoute: AuthenticatedDealsIdRoute,
  AuthenticatedJoinCodeRoute: AuthenticatedJoinCodeRoute,
  AuthenticatedMessagesIdRoute: AuthenticatedMessagesIdRoute,
  AuthenticatedCapitalIndexRoute: AuthenticatedCapitalIndexRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CommunitiesRoute: CommunitiesRoute,
  InvestorsRoute: InvestorsRoute,
  JourneyRoute: JourneyRoute,
  OperatorRoute: OperatorRoute,
  PlatformRoute: PlatformRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  EventsSlugRoute: EventsSlugRoute,
  FounderIdRoute: FounderIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
